version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  scraper:
    build: ./scraper
    depends_on:
      - kafka

  consumer:
    build: ./consumer
    depends_on:
      - kafka
    volumes:
      - ./consumer/data.json:/app/data.json

  api:
    build: ./api
    depends_on:
      - consumer
    ports:
      - "5000:5000"
    volumes:
      - ./consumer/data.json:/app/data.json
